$bg0 = rgb(0B1020)
$bg1 = rgb(11182B)
$bg2 = rgb(18233B)
$bg3 = rgb(22304A)
$bg4 = rgb(334866)

$fg = rgb(D6E4FF)

$red    = rgb(FF5D73)
$orange = rgb(F8BD96)
$yellow = rgb(F9E2AF)
$green  = rgb(6EE7B7)
$aqua   = rgb(67E8F9)
$blue   = rgb(7AA2F7)
$purple = rgb(B48EFD)
$pink   = rgb(F472B6)

$grey0 = rgb(162033)
$grey1 = rgb(334155)
$grey2 = rgb(94A3B8)

# aurora.conf
$accent1 = $blue
$accent2 = $purple
