$bg0 = rgb(151110)
$bg1 = rgb(1B263B)

$fg = rgb(DAFDFE)

$red = rgb(ff5f5f)
$orange = rgb(ff9f43)
$yellow = rgb(feca57)
$green = rgb(1dd1a1)
$aqua = rgb(48dbfb)
$blue = rgb(54a0ff)
$purple = rgb(5f27cd)
$pink = rgb(ff6bcb)

$grey0 = rgb(555555)
$grey1 = rgb(777777)
$grey2 = rgb(999999)

# blue.conf
$accent1 = $blue
$accent2 = $aqua
