$bg0 = rgb(0B0609)
$bg1 = rgb(160B12)
$bg2 = rgb(241018)
$bg3 = rgb(3A1721)
$bg4 = rgb(572437)

$fg = rgb(FBECEF)

$red = rgb(FF4D6D)
$orange = rgb(F9844A)
$yellow = rgb(F9C74F)
$green = rgb(90BE6D)
$aqua = rgb(43BCCD)
$blue = rgb(5DA9E9)
$purple = rgb(9D4EDD)
$pink = rgb(FF70A6)

$grey0 = rgb(140A10)
$grey1 = rgb(41212B)
$grey2 = rgb(8B5E69)

# crimson-void.conf
$accent1 = $red
$accent2 = $orange
