$bg0 = rgb(1E1F29)
$bg1 = rgb(232530)
$bg2 = rgb(282A36)
$bg3 = rgb(44475A)
$bg4 = rgb(6272A4)

$fg = rgb(F8F8F2)

$red = rgb(FF5555)
$orange = rgb(FFB86C)
$yellow = rgb(F1FA8C)
$green = rgb(50FA7B)
$aqua = rgb(8BE9FD)
$blue = rgb(BD93F9)
$purple = rgb(FF79C6)
$pink = rgb(FF92DF)

$grey0 = rgb(6272A4)
$grey1 = rgb(7E8AAE)
$grey2 = rgb(A4B1CD)

# dracula.conf
$accent1 = $pink
$accent2 = $purple
