$bg0 = rgb(272E33)
$bg1 = rgb(2E383C)
$bg2 = rgb(374145)
$bg3 = rgb(414B50)
$bg4 = rgb(495156)

$fg = rgb(D3C6AA)

$red = rgb(E67E80)
$orange = rgb(E69875)
$yellow = rgb(DBBC7F)
$green = rgb(A7C080)
$aqua = rgb(83C092)
$blue = rgb(7FBBB3)
$purple = rgb(D699B6)
$pink = rgb(E6A0C4)

$grey0 = rgb(5C6A72)
$grey1 = rgb(7A8478)
$grey2 = rgb(859289)

# everforest.conf
$accent1 = $green
$accent2 = $yellow
