$bg0 = rgb(09131B)
$bg1 = rgb(10202B)
$bg2 = rgb(18303D)
$bg3 = rgb(274455)
$bg4 = rgb(3B6278)

$fg = rgb(E6F7FF)

$red = rgb(FF7B72)
$orange = rgb(F6BD60)
$yellow = rgb(F9E2AF)
$green = rgb(98ECBD)
$aqua = rgb(7FE7DC)
$blue = rgb(74C7EC)
$purple = rgb(B4BEFE)
$pink = rgb(F5BDE6)

$grey0 = rgb(10202B)
$grey1 = rgb(355364)
$grey2 = rgb(8BA4B0)

# frostbyte.conf
$accent1 = $aqua
$accent2 = $grey2
