$bg0 = rgb(1D2021)
$bg1 = rgb(282828)
$bg2 = rgb(32302F)
$bg3 = rgb(3C3836)
$bg4 = rgb(504945)

$fg = rgb(EBDBB2)

$red    = rgb(FB4934)
$orange = rgb(FE8019)
$yellow = rgb(FABD2F)
$green  = rgb(B8BB26)
$aqua   = rgb(8EC07C)
$blue   = rgb(83A598)
$purple = rgb(D3869B)
$pink   = rgb(F2C7B7)

$grey0 = rgb(665C54)
$grey1 = rgb(7C6F64)
$grey2 = rgb(A89984)
# gruvbox-dark.conf
$accent1 = $orange
$accent2 = $yellow
