$bg0 = rgb(181616)
$bg1 = rgb(1F1F28)
$bg2 = rgb(2A2A37)
$bg3 = rgb(363646)
$bg4 = rgb(54546D)

$fg = rgb(DCD7BA)

$red = rgb(C4746E)
$orange = rgb(B6927B)
$yellow = rgb(DCA561)
$green = rgb(87A987)
$aqua = rgb(7AA89F)
$blue = rgb(8BA4B0)
$purple = rgb(A292A3)
$pink = rgb(D27E99)

$grey0 = rgb(727169)
$grey1 = rgb(938AA9)
$grey2 = rgb(A6A69C)

# kanagawa.conf
$accent1 = $yellow
$accent2 = $blue
