$bg0 = rgb(2E3440)
$bg1 = rgb(3B4252)
$bg2 = rgb(434C5E)
$bg3 = rgb(4C566A)
$bg4 = rgb(616E88)

$fg = rgb(ECEFF4)

$red = rgb(BF616A)
$orange = rgb(D08770)
$yellow = rgb(EBCB8B)
$green = rgb(A3BE8C)
$aqua = rgb(8FBCBB)
$blue = rgb(81A1C1)
$purple = rgb(B48EAD)
$pink = rgb(D8A4C7)

$grey0 = rgb(677691)
$grey1 = rgb(7B88A1)
$grey2 = rgb(A3B1C6)

# nord.conf
$accent1 = $blue
$accent2 = $aqua
