$bg0 = rgb(0F0B12)
$bg1 = rgb(17111D)
$bg2 = rgb(241827)
$bg3 = rgb(332336)
$bg4 = rgb(4C3A4F)

$fg = rgb(F6EAF2)

$red = rgb(F7768E)
$orange = rgb(F4A261)
$yellow = rgb(E9C46A)
$green = rgb(7FC8A9)
$aqua = rgb(64DFDF)
$blue = rgb(7AA2F7)
$purple = rgb(B388EB)
$pink = rgb(FF74B1)

$grey0 = rgb(17111D)
$grey1 = rgb(433041)
$grey2 = rgb(8D7A8B)

# obsidian-rose.conf
$accent1 = $pink
$accent2 = $red
