$bg0 = rgb(191724)
$bg1 = rgb(1F1D2E)
$bg2 = rgb(26233A)
$bg3 = rgb(403D52)
$bg4 = rgb(524F67)

$fg = rgb(E0DEF4)

$red = rgb(EB6F92)
$orange = rgb(F6C177)
$yellow = rgb(EBCB8B)
$green = rgb(31748F)
$aqua = rgb(9CCFD8)
$blue = rgb(C4A7E7)
$purple = rgb(907AA9)
$pink = rgb(EBBCBA)

$grey0 = rgb(6E6A86)
$grey1 = rgb(908CAA)
$grey2 = rgb(B4B0D0)

# rose-pine.conf
$accent1 = $pink
$accent2 = $green
