$bg0 = rgb(15121A)
$bg1 = rgb(201927)
$bg2 = rgb(2B2234)
$bg3 = rgb(3A314B)
$bg4 = rgb(564A6A)

$fg = rgb(FCEFF9)

$red = rgb(FF7A90)
$orange = rgb(FFB86C)
$yellow = rgb(F9E2AF)
$green = rgb(A6E3A1)
$aqua = rgb(89DCEB)
$blue = rgb(89B4FA)
$purple = rgb(CBA6F7)
$pink = rgb(F5C2E7)

$grey0 = rgb(211B29)
$grey1 = rgb(544A63)
$grey2 = rgb(A59DB8)

# sakura-night.conf
$accent1 = $pink
$accent2 = $purple
