$bg0 = rgb(002B36)
$bg1 = rgb(073642)
$bg2 = rgb(0A3B46)
$bg3 = rgb(14424D)
$bg4 = rgb(1B4D59)

$fg = rgb(EEE8D5)

$red = rgb(DC322F)
$orange = rgb(CB4B16)
$yellow = rgb(B58900)
$green = rgb(859900)
$aqua = rgb(2AA198)
$blue = rgb(268BD2)
$purple = rgb(6C71C4)
$pink = rgb(D33682)

$grey0 = rgb(586E75)
$grey1 = rgb(657B83)
$grey2 = rgb(839496)

# solarized-dark.conf
$accent1 = $yellow
$accent2 = $blue
