$bg0 = rgb(1A1010)
$bg1 = rgb(2A1716)
$bg2 = rgb(40211F)
$bg3 = rgb(5A322B)
$bg4 = rgb(7A4B3A)

$fg = rgb(F8EDE3)

$red = rgb(FF6B6B)
$orange = rgb(F7B267)
$yellow = rgb(F9E2AF)
$green = rgb(90BE6D)
$aqua = rgb(43BCCD)
$blue = rgb(5DA9E9)
$purple = rgb(C77DFF)
$pink = rgb(F15BB5)

$grey0 = rgb(241817)
$grey1 = rgb(5B3A36)
$grey2 = rgb(A37B73)

# sunset-drive.conf
$accent1 = $orange
$accent2 = $pink
