$bg0 = rgb(16161E)
$bg1 = rgb(1A1B26)
$bg2 = rgb(24283B)
$bg3 = rgb(2F3549)
$bg4 = rgb(414868)

$fg = rgb(C0CAF5)

$red = rgb(F7768E)
$orange = rgb(FF9E64)
$yellow = rgb(E0AF68)
$green = rgb(9ECE6A)
$aqua = rgb(73DACA)
$blue = rgb(7AA2F7)
$purple = rgb(9D7CD8)
$pink = rgb(BB9AF7)

$grey0 = rgb(565F89)
$grey1 = rgb(737AA2)
$grey2 = rgb(A9B1D6)

# tokyo-night.conf
$accent1 = $blue
$accent2 = $purple
