include ~/.config/kitty/colors/colors.conf
# include ./themes.conf
# =====================
# FONTE
# =====================

font_family 	GeistMono Nerd Font
font_size	13
bold_font	auto #
italic_font 	auto #

# =====================
# CURSOR
# =====================

cursor_shape beam
cursor_blick_interval 0.5

# =====================
# APARENCIA
# =====================

background_opacity 0.50
background_tint    0.92

url_color #e8eaed
url_style curly

window_padding_width 12
window_border_width  1
draw_minimal_borders yes

scrollback_lines 5000
enable_audio_bell no
allow_remote_control yes

# =====================
# SHELL
# =====================
shell zsh
shell_integration no-cursor
