foreground #D6E4FF
background #0B1020
selection_foreground #0B1020
selection_background #D6E4FF

cursor #67E8F9
cursor_text_color #0B1020

url_color #67E8F9

active_border_color #7AA2F7
inactive_border_color #334155

tab_bar_background #11182B
active_tab_background #7AA2F7
active_tab_foreground #0B1020
inactive_tab_background #18233B
inactive_tab_foreground #94A3B8

color0  #0F172A
color1  #FF5D73
color2  #6EE7B7
color3  #F9E2AF
color4  #7AA2F7
color5  #B48EFD
color6  #67E8F9
color7  #D6E4FF

color8  #334155
color9  #FF7B8D
color10 #8EF0C7
color11 #FFE6B3
color12 #96BBFF
color13 #CAB3FF
color14 #8FF3FF
color15 #FFFFFF
