# semantic palette

# bg0 #151110
# bg1 #1B263B
# bg2 #1E3A5F
# bg3 #315473
# bg4 #6A8BA9

# fg #DAFDFE

# red    #1E3A5F
# orange #315473
# yellow #6A8BA9
# green  #1F4D34
# aqua   #94F8FB
# blue   #83BCD0
# purple #6A8BA9
# pink   #C1F3F5

# grey0 #87AAAB
# grey1 #6A8BA9
# grey2 #C1F3F5


foreground #DAFDFE
background #151110

selection_foreground #151110
selection_background #DAFDFE

cursor #94F8FB
cursor_text_color #151110

url_color #83BCD0

active_border_color #83BCD0
inactive_border_color #315473

color0  #1B263B
color1  #1E3A5F
color2  #1F4D34
color3  #315473
color4  #6A8BA9
color5  #83BCD0
color6  #94F8FB
color7  #C1F3F5

color8  #87AAAB
color9  #0C2037
color10 #102320
color11 #315473
color12 #6A8BA9
color13 #83BCD0
color14 #94F8FB
color15 #C1F3F5
