foreground #F5E9DC
background #120D0A
selection_foreground #120D0A
selection_background #F5E9DC

cursor #6FB3B8
cursor_text_color #120D0A

url_color #6FB3B8

active_border_color #E6A15C
inactive_border_color #4B3A33

tab_bar_background #1F1714
active_tab_background #E6A15C
active_tab_foreground #120D0A
inactive_tab_background #2B211D
inactive_tab_foreground #A58B7B

color0  #1A1412
color1  #D97757
color2  #8AA87D
color3  #E9C46A
color4  #7DA6C2
color5  #A78BFA
color6  #6FB3B8
color7  #F5E9DC

color8  #4B3A33
color9  #F09573
color10 #A7C59A
color11 #FFE08A
color12 #9CC2DE
color13 #C4AEFF
color14 #8BD3D8
color15 #FFFFFF
