foreground #FBECEF
background #0B0609
selection_foreground #0B0609
selection_background #FBECEF

cursor #43BCCD
cursor_text_color #0B0609

url_color #43BCCD

active_border_color #9D4EDD
inactive_border_color #41212B

tab_bar_background #160B12
active_tab_background #9D4EDD
active_tab_foreground #0B0609
inactive_tab_background #241018
inactive_tab_foreground #8B5E69

color0  #140A10
color1  #FF4D6D
color2  #90BE6D
color3  #F9C74F
color4  #5DA9E9
color5  #9D4EDD
color6  #43BCCD
color7  #FBECEF

color8  #41212B
color9  #FF7591
color10 #AED48A
color11 #FFE07A
color12 #84C5FF
color13 #BE7BFF
color14 #6DE3F0
color15 #FFFFFF
