foreground #DFFBFF
background #07141D
selection_foreground #07141D
selection_background #DFFBFF

cursor #4FD1C5
cursor_text_color #07141D

url_color #4FD1C5

active_border_color #5DADE2
inactive_border_color #33556B

tab_bar_background #0D1F2A
active_tab_background #5DADE2
active_tab_foreground #07141D
inactive_tab_background #123140
inactive_tab_foreground #7FA2B8

color0  #0F202E
color1  #FF6B81
color2  #81B29A
color3  #F2CC8F
color4  #5DADE2
color5  #A78BFA
color6  #4FD1C5
color7  #DFFBFF

color8  #33556B
color9  #FF8AA0
color10 #9CCCB5
color11 #FFE0B0
color12 #84C5FF
color13 #C2AEFF
color14 #72F0E3
color15 #FFFFFF
