foreground #EAEAEA
background #000000

selection_foreground #000000
selection_background #EAEAEA

cursor #FFFFFF
cursor_text_color #000000

url_color #AAAAAA

active_border_color #BBBBBB
inactive_border_color #444444

color0  #111111
color1  #555555
color2  #777777
color3  #888888
color4  #AAAAAA
color5  #BBBBBB
color6  #CCCCCC
color7  #EAEAEA

color8  #444444
color9  #666666
color10 #888888
color11 #999999
color12 #BBBBBB
color13 #CCCCCC
color14 #DDDDDD
color15 #FFFFFF
