foreground #D3C6AA
background #272E33

selection_foreground #272E33
selection_background #D3C6AA

cursor #7FBBB3
cursor_text_color #272E33

url_color #7FBBB3

active_border_color #7FBBB3
inactive_border_color #495156

color0  #2E383C
color1  #E67E80
color2  #A7C080
color3  #DBBC7F
color4  #7FBBB3
color5  #D699B6
color6  #83C092
color7  #D3C6AA

color8  #5C6A72
color9  #E67E80
color10 #A7C080
color11 #DBBC7F
color12 #7FBBB3
color13 #D699B6
color14 #83C092
color15 #E4E1CD
