foreground #E6F7FF
background #09131B
selection_foreground #09131B
selection_background #E6F7FF

cursor #7FE7DC
cursor_text_color #09131B

url_color #7FE7DC

active_border_color #74C7EC
inactive_border_color #355364

tab_bar_background #10202B
active_tab_background #74C7EC
active_tab_foreground #09131B
inactive_tab_background #18303D
inactive_tab_foreground #8BA4B0

color0  #10202B
color1  #FF7B72
color2  #98ECBD
color3  #F9E2AF
color4  #74C7EC
color5  #B4BEFE
color6  #7FE7DC
color7  #E6F7FF

color8  #355364
color9  #FF9B93
color10 #B6FFD8
color11 #FFE6B3
color12 #98DFFF
color13 #D0D7FF
color14 #A8FFF6
color15 #FFFFFF
