foreground #EBDBB2
background #1D2021

selection_foreground #1D2021
selection_background #EBDBB2

cursor #FABD2F
cursor_text_color #1D2021

url_color #83A598

active_border_color #83A598
inactive_border_color #504945

color0  #282828
color1  #FB4934
color2  #B8BB26
color3  #FABD2F
color4  #83A598
color5  #D3869B
color6  #8EC07C
color7  #EBDBB2

color8  #928374
color9  #FB4934
color10 #B8BB26
color11 #FABD2F
color12 #83A598
color13 #D3869B
color14 #8EC07C
color15 #FBF1C7
