foreground #FFE9D6
background #140809

selection_foreground #140809
selection_background #FFE9D6

cursor #FF5A36
cursor_text_color #140809

url_color #FF7F50

active_border_color #FF5A36
inactive_border_color #5A2A27

tab_bar_background #1F0D0E

active_tab_background #FF5A36
active_tab_foreground #140809

inactive_tab_background #2A1415
inactive_tab_foreground #A56A5F

# normal
color0  #1A0D0E
color1  #FF4D2E
color2  #D65A31
color3  #FFB347
color4  #A63A28
color5  #C44536
color6  #FF7F50
color7  #FFE9D6

# bright
color8  #5A2A27
color9  #FF6F4F
color10 #E07A52
color11 #FFD089
color12 #C24B35
color13 #E85D3F
color14 #FF9A6A
color15 #FFFFFF
