foreground #DCD7BA
background #181616

selection_foreground #181616
selection_background #DCD7BA

cursor #8BA4B0
cursor_text_color #181616

url_color #8BA4B0

active_border_color #8BA4B0
inactive_border_color #54546D

color0  #1F1F28
color1  #C4746E
color2  #87A987
color3  #DCA561
color4  #8BA4B0
color5  #A292A3
color6  #7AA89F
color7  #DCD7BA

color8  #727169
color9  #C4746E
color10 #87A987
color11 #DCA561
color12 #8BA4B0
color13 #A292A3
color14 #7AA89F
color15 #C8C093
