foreground #F4EFFF
background #120B1E
selection_foreground #120B1E
selection_background #F4EFFF

cursor #2AC3DE
cursor_text_color #120B1E

url_color #2AC3DE

active_border_color #7AA2F7
inactive_border_color #44325F

tab_bar_background #1C102B
active_tab_background #C792EA
active_tab_foreground #120B1E
inactive_tab_background #29163F
inactive_tab_foreground #8A7AA6

color0  #1A1325
color1  #FF5F87
color2  #9ECE6A
color3  #F9E2AF
color4  #7AA2F7
color5  #C792EA
color6  #2AC3DE
color7  #F4EFFF

color8  #44325F
color9  #FF7AA2
color10 #B5F07D
color11 #FFE6B3
color12 #9CC0FF
color13 #DEB3FF
color14 #5FE8FF
color15 #FFFFFF
