foreground #E0DEF4
background #191724

selection_foreground #191724
selection_background #E0DEF4

cursor #C4A7E7
cursor_text_color #191724

url_color #9CCFD8

active_border_color #C4A7E7
inactive_border_color #524F67

color0  #26233A
color1  #EB6F92
color2  #31748F
color3  #F6C177
color4  #C4A7E7
color5  #EBBCBA
color6  #9CCFD8
color7  #E0DEF4

color8  #6E6A86
color9  #EB6F92
color10 #31748F
color11 #F6C177
color12 #C4A7E7
color13 #EBBCBA
color14 #9CCFD8
color15 #F2E9FF
