foreground #FCEFF9
background #15121A
selection_foreground #15121A
selection_background #FCEFF9

cursor #89DCEB
cursor_text_color #15121A

url_color #89DCEB

active_border_color #CBA6F7
inactive_border_color #544A63

tab_bar_background #201927
active_tab_background #CBA6F7
active_tab_foreground #15121A
inactive_tab_background #2B2234
inactive_tab_foreground #A59DB8

color0  #211B29
color1  #FF7A90
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #CBA6F7
color6  #89DCEB
color7  #FCEFF9

color8  #544A63
color9  #FF9DB0
color10 #C0F0BC
color11 #FFECC2
color12 #A7CAFF
color13 #DFC2FF
color14 #A8F0FF
color15 #FFFFFF
