################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,1


###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = yazi
$menu = pkill rofi || bash ~/.config/rofi/launcher.sh
$mainMod = SUPER

# Ax-Shell
# source = ~/.config/Ax-Shell/config/hypr/ax-shell.conf

# Colors
source = ~/.config/hypr/colors/colors.conf

# My Config 
source = ~/.config/hypr/configs/appearance.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/general.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybinds.conf

