general {
    gaps_in = 5
    gaps_out = 4
    border_size = 2
    col.active_border = $accent1 $accent2 45deg
    col.inactive_border = $grey1
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}
